Feature/hinweis
gematik/spec-E-Rezept-ServiceRequest pull request #17
Opened 2023-02-02 06:43 UTC by ofegem

Abschnitt überarbeitet

2023-02-02 11:20 UTC, florianschoffke requested changes
Ist das wirklich so gewollt, dass wir noch so eine Umfahrung machen wollen?
Dann wäre ja vieles von dem was wir machen hinfällig, wenn man das einfach so lösen kann :D

2023-02-02 11:20 UTC, florianschoffke commented on ImplementationGuide/markdown/KimMessages.md
>    - [KIM Dienstkennungen](#kim-dienstkennungen)
Das Inhaltsverzeichnis funktioniert noch nicht ganz, oder? Da lösen sich ja nicht alle Referenzen auf.

2023-02-02 11:43 UTC, florianschoffke commented on ImplementationGuide/markdown/KimMessages.md
>    - [KIM Rezeptanforderung](#kim-rezeptanforderung)
Das Inhaltsverzeichnis löst sich nicht korrekt auf

2023-03-01 07:24 UTC, florianschoffke commented
@SvenSommer werden wir das Umsetzen? Mein letzter Kenntnisstand ist, dass wir das nicht machen. 
Können wir das schließen?

2023-03-02 07:50 UTC, SvenSommer commented
Ich finde die Idee einer alternativen Übermittlung der Daten gar nicht schlecht.
Lass uns das nochmal mit @SimoneonFHIR und dem KIM-Team besprechen.

2023-05-05 06:56 UTC, SvenSommer commented
Idee wird im App-Transport-Framework aufgegriffen und in den jeweiligen Anwendungsfällen dann umgesetzt.

2023-05-05 06:56 UTC, closed without merging