Rename Profiles for new claim
gematik/spec-E-Rezept-ServiceRequest pull request #30
Opened 2023-05-05 09:23 UTC by florianschoffke

Rename Profiles for new claim

2023-05-05 09:56 UTC, SvenSommer requested changes

2023-05-05 09:56 UTC, SvenSommer commented on Resources/fsh-generated/resources/Bundle-UC1-1-Prescription-Request-To-Prescriber.json
> +      "fullUrl": "http://erp-servicerequest-test.de/MessageHeader/UC1-HealthCareService-to-Practitioner-MessageHeader",
-test.de?

2023-05-05 09:56 UTC, SvenSommer commented on Resources/fsh-generated/resources/Bundle-UC1-2-Fullfilled-Prescription-Request.json
> +      "fullUrl": "http://erp-servicerequest-test.de/MessageHeader/UC1-Practitioner-to-HealthCareService-MessageHeader",
hier auch

2023-05-05 09:56 UTC, SvenSommer commented on Resources/input/fsh/examples/UC1_Storno/UC1_Storno_Bundles.fsh
> +* entry[0].fullUrl = "http://erp-servicerequest-test.de/MessageHeader/UC1-Pharmacy-to-HealthCareService-MessageHeader-Storno"
Hier ist die Quelle

2023-05-05 10:11 UTC, SvenSommer commented on Resources/fsh-generated/resources/Bundle-UC1-1-Prescription-Request-To-Prescriber.json
> +      "fullUrl": "http://erp-servicerequest-test.de/MessageHeader/UC1-HealthCareService-to-Practitioner-MessageHeader",
Bite auf uuid mit GUID umstellen

2023-05-05 12:35 UTC, florianschoffke commented on Resources/fsh-generated/resources/Bundle-UC1-1-Prescription-Request-To-Prescriber.json
> +      "fullUrl": "http://erp-servicerequest-test.de/MessageHeader/UC1-HealthCareService-to-Practitioner-MessageHeader",
wie besprochen -> won't fix

2023-05-09 06:43 UTC, SvenSommer approved these changes

2023-05-09 09:25 UTC, merged