Verbesserungen durch Kommentierung
gematik/spec-E-Rezept-ServiceRequest pull request #34
Opened 2023-05-31 04:39 UTC by florianschoffke

2023-05-31 11:39 UTC, SvenSommer requested changes

2023-05-31 11:39 UTC, SvenSommer commented on Resources/fsh-generated/resources/Bundle-UC1-2-Fullfilled-Prescription-Request.json
Ich denke die RequestingOrganisation kann ebenfalls raus https://github.com/gematik/spec-E-Rezept-ServiceRequest/pull/34/files#diff-f4848bdf9947275d57cb641cac06862c8c622fc0bfb89890080f7971e55a7529L515

2023-05-31 11:39 UTC, SvenSommer commented on Resources/input/fsh/examples/UC1/UC1_Bundles.fsh
>  * entry[+].fullUrl = "http://erp-servicerequest-test.de/Organization/Example-HealthCareService-Organization"
Die RequestingOrganisation muss nicht wieder zurück geschickt werden.

2023-06-01 06:14 UTC, florianschoffke commented on Resources/input/fsh/examples/UC1/UC1_Bundles.fsh
>  * entry[+].fullUrl = "http://erp-servicerequest-test.de/Organization/Example-HealthCareService-Organization"
ServiceRequest.requester ist 1..1, muss damit also referenziert werden. Durch den Bundle constraint, dass sich alles auflösen muss, muss die anfragende Organisation zurückgegeben werden.

2023-06-01 08:40 UTC, SvenSommer commented on Resources/input/fsh/examples/UC1/UC1_Bundles.fsh
>  * entry[+].fullUrl = "http://erp-servicerequest-test.de/Organization/Example-HealthCareService-Organization"
ok, guter Hinweis.

2023-06-01 08:41 UTC, SvenSommer approved these changes

2023-06-01 09:11 UTC, merged